---
- name: Ensure sytem.conf.d directory
  ansible.builtin.file:
    path: /etc/systemd/system.conf.d
    state: directory
    mode: 0755

- name: Copy watchdog.conf file
  ansible.builtin.template:
    src: watchdog.conf.j2
    dest: /etc/systemd/system.conf.d/watchdog.conf
    backup: yes
  notify: reexec systemd
