---
- name: Set default release version
  ansible.builtin.copy:
    src: 99target
    dest: /etc/apt/apt.conf.d/99target
    backup: yes

- name: Copy sources.list
  ansible.builtin.copy:
    src: sources.list
    dest: /etc/apt/sources.list
    backup: yes

- name: Update cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install packages
  ansible.builtin.apt:
    name: "{{packages}}"
    state: latest
    update_cache: yes
