---
- name: Copy wpa_supplicant.conf file
  ansible.builtin.template:
    src: wpa_supplicant.conf.j2
    dest: /etc/wpa_supplicant/wpa_supplicant.conf
    backup: yes
  notify: restart wpa_supplicant
