- name: Generate locale
  locale_gen:
    name: "{{item}}"
    state: present
  with_items: "{{locales}}"

- name: Update locale
  shell: |
    dpkg-reconfigure --frontend noninteractive locales
    update-locale LANG={{locales[0]}} LANGUAGE={{locales[0]}} LC_ALL={{locales[0]}}

- name: Set timezone
  shell: |
    echo {{timezone}} > /etc/timezone
    dpkg-reconfigure --frontend noninteractive tzdata
