---
- name: Install docker
  ansible.builtin.apt:
    name:
      - "docker.io"
      - kubernetes-client
    state: latest
    update_cache: yes

- name: Copy daemon.json
  ansible.builtin.copy:
      src: daemon.json
      dest: /etc/docker/daemon.json
      backup: yes
  notify: restart docker
