---
- name: "Install docker"
  ansible.builtin.apt:
      name:
          - "docker.io"
          - "kubernetes-client"
      state: "latest"
      update_cache: true

- name: "Copy daemon.json"
  ansible.builtin.copy:
      src: "daemon.json"
      dest: "/etc/docker/daemon.json"
      backup: true
  notify: "restart docker"
